Fix lint errors
  /github/workspace/tests/framework_bottle/test_application.py:18:1: F401 'webtest' imported but unused
  /github/workspace/tests/framework_bottle/test_application.py:37:1: F811 redefinition of unused 'version' from line 19
  /github/workspace/tests/framework_bottle/test_application.py:229:5: F401 'newrelic.agent' imported but unused