Check for None before accessing transaction settings (#18)
* Check for enabled flag before accessing transaction settings

This issues happened with Tornado. Within async POST handler, if we finish the request with self.finish() before using AsyncHttp client for making a http request, the transaction is 'exited' with settings set to None. But we land up in generate_request_headers with 'transaction' not set to None but transaction.settings None, leading to exception:

Traceback (most recent call last):
  File "/home/ketan/repo/iot/newrelic/iot-data-manager/services/common/asynchttp.py", line 24, in fetch
    async_http_response = await http_client.fetch(url)
  File "/home/ketan/.local/lib/python3.6/site-packages/newrelic/hooks/framework_tornado.py", line 284, in wrap_httpclient_fetch
    outgoing_headers = trace.generate_request_headers(current_transaction())
  File "/home/ketan/.local/lib/python3.6/site-packages/newrelic/api/cat_header_mixin.py", line 92, in generate_request_headers
    if settings.distributed_tracing.enabled:
AttributeError: 'NoneType' object has no attribute 'distributed_tracing'


Added check for transaction.enabled.

* Support Python 2.7

Test was failing for Python 2.7. Apparently transaction.enabled does not exist for Python 2.7. Fixed it by directly checking transaction.settings.