Some linter fixes (#679)
* Some linter fixes

* Fix bandit finding CWE-327: Use of weak MD5 hash

```
  >> Issue: [B324:hashlib] Use of weak MD4, MD5, or SHA1 hash for security. Consider usedforsecurity=False
     Severity: High   Confidence: High
     CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
     Location: /github/workspace/newrelic/common/encoding_utils.py:270:30
     More Info: https://bandit.readthedocs.io/en/1.7.4/plugins/b324_hashlib.html
  269
  270	    path_hash = rotated ^ int(hashlib.md5(name).hexdigest()[-8:], base=16)
  271	    return "%08x" % path_hash
```

This is encrypting the app name and the transaction name which are not anything supper
secret. Set `usedforsecurity=False` to indicate this.

* Fix bandit finding CWE-78: use of exec detected

```
  >> Issue: [B102:exec_used] Use of exec detected.
     Severity: Medium   Confidence: High
     CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
     Location: /github/workspace/newrelic/common/async_wrapper.py:27:4
     More Info: https://bandit.readthedocs.io/en/1.7.4/plugins/b102_exec_used.html
  26	    values = {"wrapper": None, "wrapped": wrapped, "trace": trace, "functools": functools}
  27	    exec(wrapper_string, values)
  28	    return values["wrapper"]
----------------------------------------------------------------------------------
  >> Issue: [B102:exec_used] Use of exec detected.
     Severity: Medium   Confidence: High
     CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
     Location: /github/workspace/newrelic/hooks/framework_tornado.py:261:4
     More Info: https://bandit.readthedocs.io/en/1.7.4/plugins/b102_exec_used.html
  260	    )
  261	    exec(wrapper, values)
  262	    return values["wrapper"]
```
This is not an issue in these two cases since the function string is hardcoded. The only
user input here are the values to the function that we are wrapping which are a
non-issue.

* Fix bandit issue B108: insecure usage of temp file

```
 >> Issue: [B108:hardcoded_tmp_directory] Probable insecure usage of temp file/directory.
     Severity: Medium   Confidence: Medium
     CWE: CWE-377 (https://cwe.mitre.org/data/definitions/377.html)
     Location: /github/workspace/newrelic/admin/license_key.py:41:19
     More Info: https://bandit.readthedocs.io/en/1.7.4/plugins/b108_hardcoded_tmp_directory.html
  40	    else:
  41	        log_file = "/tmp/python-agent-test.log"
  42

  --------------------------------------------------
  >> Issue: [B108:hardcoded_tmp_directory] Probable insecure usage of temp file/directory.
     Severity: Medium   Confidence: Medium
     CWE: CWE-377 (https://cwe.mitre.org/data/definitions/377.html)
     Location: /github/workspace/newrelic/admin/local_config.py:41:19
     More Info: https://bandit.readthedocs.io/en/1.7.4/plugins/b108_hardcoded_tmp_directory.html
  40	    else:
  41	        log_file = "/tmp/python-agent-test.log"
  42

  --------------------------------------------------
  >> Issue: [B108:hardcoded_tmp_directory] Probable insecure usage of temp file/directory.
     Severity: Medium   Confidence: Medium
     CWE: CWE-377 (https://cwe.mitre.org/data/definitions/377.html)
     Location: /github/workspace/newrelic/admin/network_config.py:41:19
     More Info: https://bandit.readthedocs.io/en/1.7.4/plugins/b108_hardcoded_tmp_directory.html
  40	    else:
  41	        log_file = "/tmp/python-agent-test.log"
  42
```
These files are used to log info about the agent and the application. If someone
gets a hold of these it's ok. There is also not a risk of someone opening a different
file here since we hardcode the file path.

* Fix W0622: Redefining built-in 'help'

* Fix pylint open errors

```
newrelic/admin/debug_console.py:41:21: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
newrelic/admin/debug_console.py:41:21: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
newrelic/admin/generate_config.py:37:14: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
newrelic/admin/generate_config.py:37:14: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
newrelic/admin/generate_config.py:43:22: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
newrelic/admin/generate_config.py:43:22: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
```
Because we still support python2.7 and open in 2.7 does not have a encoding attr, leave
these as is and ignore the error.

* Fix unused import & ignore pos args before args

```
newrelic/admin/record_deploy.py:128:4: W1113: Keyword argument before variable positional arguments list in the definition of _args function (keyword-arg-before-vararg)
newrelic/admin/record_deploy.py:21:0: W0611: Unused certs imported from newrelic.common (unused-import)
```
Python 2.7 requires *args to be at end of params list so ignore this error.
Remove unused import.

* Fix bandit and lint errors in run_python.py

```
  >> Issue: [B606:start_process_with_no_shell] Starting a process without a shell.
     Severity: Low   Confidence: Medium
     CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
     Location: /github/workspace/newrelic/admin/run_python.py:110:4
     More Info: https://bandit.readthedocs.io/en/1.7.4/plugins/b606_start_process_with_no_shell.html
  109
  110	    os.execl(python_exe_path, python_exe_path, *args)
```
Since this command is only ever executed by launching the newrelic-admin script which
already requires some kind of priveledged access in the first place, ignore this bandit
error.

```
newrelic/admin/run_python.py:67:4: W0611: Unused version imported from newrelic (unused-import)
newrelic/admin/run_python.py:17:0: W0611: Unused usage imported from newrelic.admin (unused-import)
```
Remove unused imports.

Change `not x in y` to `x not in y`.

* Ignore bandit tmp dir & fix implicit str concat

* Fix pylint errors

```
newrelic/api/background_task.py:77:11: C0123: Use isinstance() rather than type() for a typecheck. (unidiomatic-typecheck)
newrelic/api/background_task.py:102:11: W0125: Using a conditional statement with a constant value (using-constant-test)
newrelic/api/background_task.py:113:12: C2801: Unnecessarily calls dunder method __enter__. Invoke context manager directly. (unnecessary-dunder-call)
```

* Fix lint errors

```
newrelic/api/error_trace.py:23:4: W0102: Dangerous default value [] as argument (dangerous-default-value)
newrelic/api/error_trace.py:41:0: W1404: Implicit string concatenation found in call (implicit-str-concat)
newrelic/api/error_trace.py:63:0: W0102: Dangerous default value [] as argument (dangerous-default-value)
newrelic/api/error_trace.py:76:0: W0102: Dangerous default value [] as argument (dangerous-default-value)
newrelic/api/error_trace.py:86:0: W0102: Dangerous default value [] as argument (dangerous-default-value)
```

* Fix pylint errors

```
************* Module newrelic.api.function_profile
newrelic/api/function_profile.py:34:8: W0107: Unnecessary pass statement (unnecessary-pass)
************* Module newrelic.api.generator_trace
newrelic/api/generator_trace.py:91:59: E1133: Non-iterable value exc is used in an iterating context (not-an-iterable)
************* Module newrelic.api.in_function
newrelic/api/in_function.py:17:0: W0611: Unused InFunctionWrapper imported from newrelic.common.object_wrapper (unused-import)
newrelic/api/in_function.py:17:0: W0611: Unused in_function imported from newrelic.common.object_wrapper (unused-import)
newrelic/api/in_function.py:17:0: W0611: Unused wrap_in_function imported from newrelic.common.object_wrapper (unused-import)
************* Module newrelic.api.lambda_handler
newrelic/api/lambda_handler.py:64:9: W0511: FIXME Should this allow for multiple apps if a string. (fixme)
newrelic/api/lambda_handler.py:167:0: W1404: Implicit string concatenation found in call (implicit-str-concat)
************* Module newrelic.api.log
newrelic/api/log.py:79:21: W0622: Redefining built-in 'object' (redefined-builtin)
************* Module newrelic.api.message_trace
newrelic/api/message_trace.py:94:0: W0102: Dangerous default value {} as argument (dangerous-default-value)
newrelic/api/message_trace.py:156:0: W0102: Dangerous default value {} as argument (dangerous-default-value)
newrelic/api/message_trace.py:168:0: W0102: Dangerous default value {} as argument (dangerous-default-value)
```

* Fix pylint errors

```
newrelic/api/out_function.py:17:0: W0611: Unused OutFunctionWrapper imported from newrelic.common.object_wrapper (unused-import)
newrelic/api/out_function.py:17:0: W0611: Unused out_function imported from newrelic.common.object_wrapper (unused-import)
newrelic/api/out_function.py:17:0: W0611: Unused wrap_out_function imported from newrelic.common.object_wrapper (unused-import)
************* Module newrelic.api.post_function
newrelic/api/post_function.py:17:0: W0611: Unused PostFunctionWrapper imported from newrelic.common.object_wrapper (unused-import)
newrelic/api/post_function.py:17:0: W0611: Unused post_function imported from newrelic.common.object_wrapper (unused-import)
newrelic/api/post_function.py:17:0: W0611: Unused wrap_post_function imported from newrelic.common.object_wrapper (unused-import)
************* Module newrelic.api.pre_function
newrelic/api/pre_function.py:17:0: W0611: Unused PreFunctionWrapper imported from newrelic.common.object_wrapper (unused-import)
newrelic/api/pre_function.py:17:0: W0611: Unused pre_function imported from newrelic.common.object_wrapper (unused-import)
newrelic/api/pre_function.py:17:0: W0611: Unused wrap_pre_function imported from newrelic.common.object_wrapper (unused-import)
```

* Fix pylint errors & remove FIXME

```
************* Module newrelic.api.settings
newrelic/api/settings.py:26:0: W1404: Implicit string concatenation found in assignment (implicit-str-concat)
************* Module newrelic.api.time_trace
newrelic/api/time_trace.py:216:16: W1201: Use lazy % formatting in logging functions (logging-not-lazy)
************* Module newrelic.api.web_transaction
newrelic/api/web_transaction.py:45:0: W1404: Implicit string concatenation found in assignment (implicit-str-concat)
newrelic/api/web_transaction.py:416:20: E1205: Too many arguments for logging format string (logging-too-many-args)
newrelic/api/web_transaction.py:517:16: E1205: Too many arguments for logging format string (logging-too-many-args)
```

* Fix pylint error

```
newrelic/api/web_transaction.py:587:17: R1714: Consider merging these comparisons with 'in' by using 'key in ('HTTP_CONTENT_LENGTH', 'HTTP_CONTENT_TYPE')'. Use a set instead if elements are hashable. (consider-using-in)
```

* Fix different number of arguments pylint error

```
newrelic/api/web_transaction.py:802:4: W0221: Number of parameters was 3 in 'WebTransaction.process_response' and is now 4 in overridden 'WSGIWebTransaction.process_response' method (arguments-differ)
```

* Add ObjectWrapper import back

* Fix pylint errors: dangerous default value

```
tests/testing_support/validators/validate_slow_sql_collector_json.py:23:0: W0102: Dangerous default value set() (builtins.set) as argument (dangerous-default-value)
tests/testing_support/validators/validate_slow_sql_collector_json.py:23:0: W0102: Dangerous default value set() (builtins.set) as argument (dangerous-default-value)
```

* Fix missing assert in tests

* Globally disable pylint warning about arg order

W1113: Keyword argument before variable positional arguments list in the definition
Since Python2.7 requires args and kwargs be last in the list of params we cannot fix
the above errors so just globally disable them.

* Fix W0102: Dangerous default value

* Replace == or == with in ()

* Ignore import order & use isinstance

Co-authored-by: Hannah Stepanek <hstepanek@newrelic.com>